# See https://pre-commit.com for more informatio
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^conda/
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
  - id: mixed-line-ending
    args: ['--fix=lf']
